name: code-review

on:
  pull_request:

jobs:
  code-review:
    runs-on: [self-hosted, appendix-reviewer]
    steps:
      - uses: actions/checkout@v4
      - name: Say hi
        run: echo "Hi from my self-hosted runner"